m2html('mfiles','MichalDataAna',...
       'htmldir','doc', ...
       'recursive','off', ...
       'global','on',...
       'globalHypertextLinks','on',...
       'template','blue',...
       'index','menu', ...
       'graph','on');