% FIG.3: data files generated by runFAassem.m/ ExtractAssemFA.m
%
% (c) 2014 Daniel Durstewitz, Bernstein Center for Computational Neuroscience, CIMH/ Heidelberg University
% Edited by Aleksander PF Domanski PhD UoB 2015
% aleks.domanski@bristol.ac.uk

clear all
close all
%figure(3), hold off cla
% pp=genpath('/home/dd/bin/MLana'); addpath(pp);
target= 'LONG';
pat=[target '/'];
% pat =pwd


%% Decoding assembly vs. non-assembly units
load([pat 'SpecAssemRole']);    % from SpecRoleAssemU.m
yIN=[]; yOUT=[];
for s=1:4
    kk=find(~isnan(avgTSin(:,s)) & ~isnan(avgTSout(:,s)));
    disp((avgTSin(kk,s)>avgTSout(kk,s))')
    [h,p]=ttest(avgTSin(kk,s),avgTSout(kk,s)); disp(p)
    if s>2, yIN=[yIN avgTSin(kk,s)']; yOUT=[yOUT avgTSout(kk,s)']; end;
end;
%subplot(3,2,6), hold off cla
plot([1 2]'*ones(size(yIN)),[yIN;yOUT],'bo-','LineWidth',2); xlim([0 3]);
[~,p]=ttest(yIN',yOUT'); 
text(2,1.4,['p < ' num2str(round(p*1e3)*1e-3)],'FontSIze',16);
box off; ylabel('Decoding (F-score)');
set(gca,'FontSize',20,'XTick',[1 2],'XTickLabel',{'assem units','non-assem units'});


%% determining number of signif. factors
% subplot(3,2,1), hold off cla
% A=dir([pat '*PFC_iFR50*.mat']);
% A=dir(['*LONG*.mat']);
A=dir(['*' target '*.mat']);

for i=1:length(A)
    k=findstr(A(i).name,'_'); r=findstr(A(i).name,'.'); 
    Name{i}=[A(i).name(1:k(1)) A(i).name(k(2)+1:r-1)];
end;
f=5; s=3; alpha=0.01;
% for f=1:length(A)
Name{f}='JaroslawLONG1_iFR50'
    fnOut=[pat Name{f} '_AssemRes2']; load(fnOut);
Name{f}='JaroslawLONG1_iFR50'
    fnOut=[pat Name{f} '_FSC']; load(fnOut);
Name{f}='JaroslawLONG1_iFR50'
    fnOut=[pat Name{f} '__FSCtemp']; load(fnOut);


% z=diff(LL{s}); Zbs=diff(LLbs{s}')';
% x=2:length(z)+1; plot(x,z,'b','LineWidth',3);
% r=round(length(Zbs)*alpha); zz=sort(Zbs,'descend');
% hold on, plot(x,zz(r)*ones(1,length(z)),'r--','LineWidth',3);
% set(gca,'FontSize',22), box off
% xlabel('Factor (# assemblies)'), ylabel('log-likelihood-ratio')
% legend('original','trial-permutation (99% CI)'), legend('boxoff')
% end

for s=1:length(LL)
        figure
        z=diff(LL{s});
        Zbs=diff(LLbs{s}')';
        x=2:length(z)+1;
        subplot(1,2,1), hold off cla, plot(x,z,'b','LineWidth',2);
        %hold on, plot(Zbs','r');
        r=round(length(Zbs)*alpha); zz=sort(Zbs,'descend');
        hold on, plot(x,zz(r)*ones(1,length(z)),'r--','LineWidth',2); % plot Confidence limit
        set(gca,'FontSize',22), box off
        title(['(' num2str(f) ',' num2str(s) '): ' num2str(nassem{s})]);
        xlabel('Factor (# assemblies)'), ylabel('log-likelihood-ratio')
        legend('original','trial-permutation'), legend('boxoff')
        subplot(1,2,2), hold off cla
        vs=cell2mat(FLbs{s}{2});
        x=-0.5:0.005:0.5; h=histc(vs(1:end),x)./length(vs(1:end));
        plot(x,h,'b',[ciHld(s,2) ciHld(s,2)],[0 0.05],'g','LineWidth',2);
        hold on, plot(FL{s}{2}(1:end),0.01,'r.'); xlim([min(x) max(x)]);
        set(gca,'FontSize',22), box off
        
%         subplot(1,3,3), hold off cla
%         ws=sort(FSCbs{s}(1:end),'ascend');
%         ciV=[0.1 0.05 0.01 5e-3 1e-3];
%         for i=1:length(ciV)
%             ciLsc(s,i)=ws(round(length(ws)*ciV(i)));
%             ciHsc(s,i)=ws(round(length(ws)*(1-ciV(i))));
%         end;
%         x=-3:0.1:3; h=histc(ws,x)./length(ws);
%         plot(x,h,'b',[ciHsc(s,2) ciHsc(s,2)],[0 0.05],'g','LineWidth',2);
%         hold on, plot(FSC{s}(1:end),0.01,'r.'); xlim([min(x) max(x)]);
%         set(gca,'FontSize',22), box off
%         
%         a=input('...');
    end;

%% example of assembly activations
subplot(3,2,2), hold off cla
f=1; s=3; fn=[pat Name{f} '_FSC']; load(fn);
N=2;%18
%k=findstr(Name{f},'_'); fn2=[pat Name{f}(1:k) 'STPat50a01']; load(fn2); %L2 for even numbers!!!
k=findstr(Name{f},'_'); fn2=[pat Name{f}(1:k) 'PFC_iFR50.mat']; load(fn2); %L2 for even numbers!!!
% 
EvtTs=reshape(EvtT,2,round(length(EvtT)/2))';  EvtTs=mat2cell(EvtTs,ones(size(EvtTs,1),1),2);
EvtLs =reshape(EvtL,2,round(length(EvtL)/2))'; EvtLs =mat2cell(EvtLs,ones(size(EvtLs,1),1),2);

L=cellfun(@length,units{s}); [L,k]=sort(L,'descend');
Za=FSC
Lag=zeros(size(Za{1},2));
% [ActT,Za]=ShowAssemByTrialG(Za,Tmtx,STPat,EvtT,EvtL,Lag,crit,show)
[ActT,Zb]=ShowAssemByTrialG(Za(N),...
                            Tmtx,...%Tmtx(N)
                            units{s}(1),...(k(1:3)),...
                            EvtTs(N),...
                            EvtLs(N),...
                            Lag,...
                            0.66);
xlim([7485 7495])


%% average assembly activation by factor score
%subplot(3,2,4), hold off cla
%load 'paper2014/KrzysztofLONG1_example_assembly.mat'
% load 'KrzysztofLONG2_iFR50_AssemRes2.mat'   

% plot(1:length(y.FSCsel),y.FSCsel(:,1),'k');
subplot(3,1,1);hold on
plot(1:length(FSC{1}),FSC{1}(:,:),'r');
%put sample lever presentation and press
line([1598 1598],[-0.5 5],'Color','g','LineStyle','--', 'Linewidth',3);
line([1700 1700],[-0.5 5],'Color','g', 'Linewidth',3);
set(gca,'FontSize',12), box off
xlabel('Time (s)'); ylabel('Assembly activation');
set(gca,'xlim',[1500 1800],'ylim',[-0.5 5]); 
legend('PFC')

subplot(3,1,2);hold on
plot(1:length(FSC{2}),FSC{2}(:,:),'b');
%put sample lever presentation and press
line([1598 1598],[-0.5 5],'Color','g','LineStyle','--', 'Linewidth',3);
line([1700 1700],[-0.5 5],'Color','g', 'Linewidth',3);
set(gca,'FontSize',12), box off
xlabel('Time (s)'); ylabel('Assembly activation');
set(gca,'xlim',[1500 1800],'ylim',[-0.5 5]); 
legend('HP')

subplot(3,1,3);hold on
plot(1:length(FSC{3}),FSC{3}(:,:),'k');
%put sample lever presentation and press
line([1598 1598],[-0.5 5],'Color','g','LineStyle','--', 'Linewidth',3);
line([1700 1700],[-0.5 5],'Color','g', 'Linewidth',3);
set(gca,'FontSize',12), box off
xlabel('Time (s)'); ylabel('Assembly activation');
set(gca,'xlim',[1500 1800],'ylim',[-0.5 5]); 
legend('HP-PFC')


%% smooth and plot
temp=zeros(size(FSC{3}));
for k=1:size(FSC{1},2)
    temp(:,k)=smooth(FSC{3}(:,k)',5);
end
temp=FSC{3};

crit= 3*ones(size(temp));

temp=temp>crit;
imagesc(temp'); colormap gray

% (c) 2014, Daniel Durstewitz, Dept. Theoretical Neuroscience, CIMH
% Mannheim/ Heidelberg University
